# Generated by Django 5.2.7 on 2025-12-10 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polygon', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path_image', models.ImageField(blank=True, null=True, upload_to='clubs/')),
                ('area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='models.area')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('zgoda', 'Zgoda'), ('neutralnie', 'Neutralnie'), ('kosa', 'Kosa')], max_length=20)),
                ('club_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_a', to='models.club')),
                ('club_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_b', to='models.club')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('club_a', 'club_b'), name='unique_club_relation'), models.CheckConstraint(condition=models.Q(('club_a', models.F('club_b')), _negated=True), name='no_self_relation')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='models.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'club')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('zgoda', 'Zgoda'), ('neutralnie', 'Neutralnie'), ('kosa', 'Kosa')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_a', to='models.club')),
                ('club_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_b', to='models.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('club_a', models.F('club_b')), _negated=True), name='no_self_ticket'), models.UniqueConstraint(fields=('user', 'club_a', 'club_b'), name='unique_ticket_per_user')],
            },
        ),
    ]
