# Generated by Django 5.2.7 on 2026-01-23 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polygon', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('object', models.CharField(max_length=255, verbose_name='Object')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity log',
                'verbose_name_plural': 'Activity logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('desc', models.TextField()),
                ('path_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='models.area')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('zgoda', 'Zgoda'), ('neutralnie', 'Neutralnie'), ('kosa', 'Kosa')], max_length=20)),
                ('club_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_a', to='models.club')),
                ('club_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_b', to='models.club')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('club_a', 'club_b'), name='unique_club_relation'), models.CheckConstraint(condition=models.Q(('club_a', models.F('club_b')), _negated=True), name='no_self_relation')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mute', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='models.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'club')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('zgoda', 'Zgoda'), ('neutralnie', 'Neutralnie'), ('kosa', 'Kosa')], max_length=20)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_a', to='models.club')),
                ('club_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_b', to='models.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('club_a', models.F('club_b')), _negated=True), name='no_self_ticket'), models.UniqueConstraint(fields=('user', 'club_a', 'club_b'), name='unique_ticket_per_user')],
            },
        ),
    ]
