# Generated by Django 5.2.7 on 2026-01-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.CharField(default='Nieznane', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='desc',
            field=models.TextField(default='Brak opisu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8),
        ),
    ]
