# Generated by Django 5.2.7 on 2026-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_notification_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='club',
            name='path_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
