# Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

# Instalacja zależności
COPY package.json package-lock.json* ./
RUN npm install

# Kopiujemy resztę projektu
COPY . .

# Vite musi nasłuchiwać na 0.0.0.0, żeby działał z Dockerem
ENV HOST=0.0.0.0

# Uruchamiamy Vite
CMD ["npm", "run", "dev"]
