services:

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"        # opcjonalnie do testów lokalnych
    networks:
      - kosy-net
    volumes:
      - db_data:/var/lib/mysql
    command: --bind-address=0.0.0.0
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    networks:
      - kosy-net
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    ports:
      - "80:80"   # dostęp publiczny przez serwer
    networks:
      - kosy-net

networks:
  kosy-net:
    driver: bridge

volumes:
  db_data: