
services:


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Montuj cały kod backendu
      - ./backend:/app
      # Montuj folder z bazą danych
      - ./backend/db_storage:/app/db_storage
    environment:
      - DJANGO_SETTINGS_MODULE=Pilkarskie_Kosy.settings
    networks:
      - kosy-net

# frontend (DEV)
  frontend:
    # Wskazujemy nowy plik Dockerfile.dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    # Montowanie wolumenów
    volumes:
      - ./frontend:/app           # 1. Twój kod nadpisuje kod w kontenerze (Hot Reload)
      - /app/node_modules         # 2. <--- TO JEST KLUCZ DO SUKCESU! (Chroni biblioteki)

    ports:
      - "3000:3000"

    # Opcjonalnie: włącz polling jeśli hot-reload nie działa na Windows/Docker Desktop
    environment:
      - WATCHPACK_POLLING=true


  # Usługa frontendu (React/Nginx)
  #frontend:
   # build:
    #  context: ./frontend
     # dockerfile: frontend/Dockerfile.prod
   # ports:
    #  - "3000:80" # Dostęp do aplikacji przez port 3000
    #networks:
     # - kosy-net
    #depends_on:
     # - backend # Uruchom dopiero, gdy backend będzie gotowy

# Definicja wspólnej sieci
networks:
  kosy-net:
    driver: bridge
