FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# System deps
RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Create non-root user
RUN adduser --disabled-password appuser
USER appuser

# Copy project
COPY --chown=appuser:appuser . .

# Collect static

EXPOSE 8000

# Production server
CMD ["gunicorn", "Pilkarskie_Kosy.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
